### ISSUE TITLE
Once an element is added to the list it can't be deleted.

### ISSUE THREAD

**Issue by jaybo** [baggachipz/q-form-builder#14]
Using QFormBuilder Demo, an item can be added to the end of the list and for a time it's available for deletion.  But as soon as the _**next**_ element is added, the garbage can icon disappears from that element seemingly permanently.  So other than rearranging the order of elements, you must start over from the beginning if an element is incorrectly added.

While this state of affairs is OK for one-off designs, it fails in the case of where the an end-user is allowed to dynamically change element ordering and remove existing entries.

I'm considering adding elements for video, audio, images, embedded iframes, and markdown for an app where the end-user is dynamically adjusting the layout.

Can the garbage can be permanently (perhaps optionally) available for each element?

**Comment by baggachipz** [comment]
Oh my god you're right, that used to work properly but doesn't now. I'm not sure when that broke. I'll work on a fix and let you know when it's done.

**Comment by baggachipz** [comment]
This was a flaw in the Demo and I have fixed it. Thanks for finding it!
