### ISSUE TITLE
Can't select to edit the field or delete

### ISSUE THREAD

**Issue by Cristiano1103** [baggachipz/q-form-builder#16]
Hello, i'ts very good, i liked, congrats!

But i have a big problem, i can't select to edit the field or delete

![Captura de Tela 2021-02-11 às 13 33 46](https://user-images.githubusercontent.com/29436479/107666880-c6f34980-6c6d-11eb-996f-edb57bef2d19.png)

like u see in photo, i can interact with the form, but in the demo it's not possible, that's why i can't edit the field.

**Comment by baggachipz** [comment]
It looks like you're missing the necessary CSS to create the correct layers. I need to add these things in by default, but as of now it needs to be added manually on the page you create. Check out: https://github.com/baggachipz/q-form-builder-demo/blob/master/src/pages/Index.vue in the `<style>` section and copy/use that.

**Comment by Cristiano1103** [comment]
ok, thanks!!

**Comment by baggachipz** [comment]
Since you are in good shape, I will close the ticket, but feel free to re-open if you have issues.
