### ISSUE TITLE
Question: рow to render final form?

### ISSUE THREAD

**Issue by Serhioromano** [baggachipz/q-form-builder#3]
OK, I see the user created a form and saved it. Now I want other users open that form without edit, just form to enter data. Is there a render component or only builder?

**Comment by baggachipz** [comment]
Yes, take a look at the "form rendering" section of the example App here: https://github.com/baggachipz/q-form-builder/blob/master/src/App.vue

**Comment by Serhioromano** [comment]
It renders the builder. UI that lets you move from the field and arrange. But after that, I what other user wee it as simple HTML markup without edit option.

**Comment by baggachipz** [comment]
The example application does both: It shows you the form builder interface, then immediately below renders those fields as a user would/could see them. Please clone and run the example app, add a field or few, and then scroll down to see them rendered for users.
