### ISSUE TITLE
Is possible to add custom field types from server side?

### ISSUE THREAD

**Issue by gfirem** [baggachipz/q-form-builder#6]
Is it possible to add custom field types from the server-side. I'm asking because I'm looking to improve one existing form builder and I need to extend the field types.

**Comment by baggachipz** [comment]
It is on the roadmap, but no not possible yet. Thanks for asking!

**Comment by gfirem** [comment]
and about the server-side rendering

**Comment by baggachipz** [comment]
I haven't tried it with SSR, but since it uses all Quasar components I see no reason why it couldn't be used that way.
