### ISSUE TITLE
Can't add to Quasar app

### ISSUE THREAD

**Issue by ShaunaMack** [baggachipz/q-form-builder#8]
Having run `yarn add q-form-builder` and added `import QFormBuilder from 'q-form-builder'` to a page I see the following error when running `quasar dev`. 

I have confirmed this with a blank project created by the quasar command line tool (i.e. `quasar create`). 

If I am missing something please let me know.

```
This dependency was not found:

* q-form-builder in ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save q-form-builder
```

**Comment by baggachipz** [comment]
I'll try to play with this today and see what is going on. There have been problems with including this library due to double-including Vue, but this seems like a different issue.

**Comment by baggachipz** [comment]
Well, that was a bad build that I had published. :/

I updated the library to v0.2.0, please update from NPM (or Yarn). I also updated the doc to include the proper syntax for usage:

```javascript
import { QFormBuilder } from 'q-form-builder'
```

Please give it a try. Cheers!

**Comment by ShaunaMack** [comment]
Thanks so much Matt! I will have another go.
